# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


version: '3'

services:

    covidvu_cime_dev:
        container_name: 'covidvu_cime_dev'
        environment:
            DEVPI_HOST             : '${DEVPI_HOST}'
            GRANT_SUDO             : 'yes'
            JUPYTER_LAB_ENABLE     : 'yes'
            PIP_TRUSTED_HOST       : '${PIP_TRUSTED_HOST}'
        image: 'pr3d4t0r/covidvu:latest'
        ports:
            - 127.0.0.1:8805:8888
            # For LAN availability:
            # - 8805:8888
        privileged: true
        user: 'root:${JUPYTER_LAB_GROUP}'
        volumes:
            - '${HOME}/covidvu:/home/jovyan'

