name: Update COVIDvu

on:
  push:
    branches:
    - master
    - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ui
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
      if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
      working-directory: ${{env.working-directory}}
    - run: NODE_OPTIONS=--max_old_space_size=4096 npm run deploy:staging
      if: github.ref == 'refs/heads/staging'
      working-directory: ${{env.working-directory}}